### ISSUE TITLE
Link Contoh error pada README.md di folder basic operator

### ISSUE THREAD

**Issue by toufiqnuur** [bellshade/JavascriptAlgorithm#109]
## Deskripsi
Link contoh file [nullish coalescing operator](https://github.com/bellshade/Javascript/blob/main/basic/003_operator/README.md#hint) error 404 not found.

## Saran kamu
Dibagian linknya ada typo bisa diganti menjadi `nullishCoalescingOperators.js`

## Screenshots atau output
Error 404 not found

## Desktop (please complete the following information):
 - OS: ```Linux```

Terima kasih !

**Comment by Vins2106** [comment]
sudah saya fix om 👍
