### ISSUE TITLE
Menambahkan Struktur Data Queue

### ISSUE THREAD

**Issue by wahyaumau** [bellshade/JavascriptAlgorithm#122]
## Deskripsi
Queue adalah struktur data linear yang mirip seperti antrian. Proses penambahan dan penghapusan data pada queue bersifat FIFO (First In First Out), yaitu data yang masuk pertama, akan diproses dan dihapus pertama pula.

### Fungsi-fungsi pada Queue
1. Enqueue, menambahkan data pada queue.
2. Dequeue, menghapus data pada queue, dan mengembalikan data yang dihapus
3. Peek, mengambil data pada queue
4. isEmpty, mengecek apakah data pada queue kosong

Terima kasih atas pehatiannya.

**Comment by reacto11mecha** [comment]
Jangan lupa nanti mention issue ini biar langsung di close pas open pull requestnya
